### ISSUE TITLE
Update ETL with new data model changes

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-etl#27]
Address changes in: https://github.com/kids-first/kf-es-model/pull/29 

- [x] Date fields have been removed from objects
- [x] Logic for hpo_ids and hpo_negative ids remains the same, but the fields been renamed `hpo_phenotype_observed` and  `hpo_phenotype_not_observed`
- [x] New fields need to be mapped in etl
> 1. `file_centric.dbgap_consent_code` needs to be added. 
 Mapping: dataservce.biospecimens.dbgap_consent_code --> participant.biospecimen.dpgap_consent_code
> 2. `snomed_phenotype_observed` and `snomed_phenotype_not_observed` (same logic as phentype not observed)
- [x] study removed from underneath family

**Comment by joneubank** [comment]
Run and working in QA.

All code merged.

Can be closed if approved (Thanks Rosi).

**Comment by rosibaj** [comment]
Tested 're_00000003' -- dates removed/new fields correctly added!
