### ISSUE TITLE
Additional ETL Fields

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-etl#30]
- [ ] **1. Add `ACL` field into ETL** 
Field source in dataservice: http://kf-api-dataservice.kids-first.io/genomic-files 
>
``` {
  "_links": {},
  "acl": [
    "phs001228",
    "phs001228.c1",
    "SD_YGVA0E1C"
  ],
  "availability": "Immediate Download",
  "controlled_access": true,
  "created_at": "2018-06-12T16:47:50.577272+00:00",
  "data_type": "gVCF",
  "external_id": null,
  "file_format": "gVCF",
  "file_name": "0010072e-8a03-4921-bb88-bd3626f6397e.g.vcf.gz",
  "hashes": {},
  "is_harmonized": true,
  "kf_id": "GF_RTXW5VK1",
  "latest_did": "eaf5fc31-d3e1-4330-a403-c885205bb89d",
  "metadata": {},
  "modified_at": "2018-07-24T15:42:57.963684+00:00",
  "reference_genome": "GRCh38",
  "size": 11898993543,
  "urls": [
    "s3://kf-study-us-east-1-prd-sd-ygva0e1c/harmonized/gvcf/0010072e-8a03-4921-bb88-bd3626f6397e.g.vcf.gz"
  ]
} 
```

ES model change: https://github.com/kids-first/kf-es-model/pull/31/files
The `acl` field was added under properties everywhere files were de

Expected result:
```
"acl": [
  "phs001228"
  "phs001228.c1"
  "SD_YGVA0E1C"
],
```

**Comment by rosibaj** [comment]
@joneubank I just realized, for the 2nd one you will need to create reference databases like HPO but for the ontologies involved in diagnosis

**Comment by rosibaj** [comment]
@joneubank Assuming you mean `participant_centric.files.acl` when you say "`files object`", these should be the same. The top level fields of `file_centric` are the same as the`participant_centric.files` properties. 

`file_centric.properties.acl` should be the acl strings from a particilar file for that document.

**Comment by joneubank** [comment]
OK that makes sense. Thanks.

**Comment by joneubank** [comment]
@rosibaj Can we split the ACL and diagnosis into separate tickets? The work required to add the reference databases will take much longer than the ACL work.

**Comment by rosibaj** [comment]
@joneubank no problem will do that now!

**Comment by rosibaj** [comment]
@hlminh2000 Adjusted: https://github.com/kids-first/kf-portal-ui/issues/744
