### ISSUE TITLE
Exclude non-visible entities from ETL indexing

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-etl#32]
- All entities in dataservice have the field `visible` now. 
- If the visible field is `FALSE` these entities should not be indexed
- Visible is hierarchal; ex. if a participant has `visible = false` then no child entities should be indexed etc

**Comment by joneubank** [comment]
@rosibaj are there any examples in the dataservice today with `visible=false` ?

**Comment by rosibaj** [comment]
@joneubank study ` MEOWMEOW` should be set to false
