### ISSUE TITLE
Additional Fields to add to ETL 

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-etl#33]
- [x] 1. Diagnosis cateogry added to Participant
     - source: http://kf-api-dataservice-qa.kids-first.io/#tag/Participant
     - should map to `participant.diagnosis_category`
- [x] 2.  `Affected Status` added to Participant
     -  source: http://kf-api-dataservice-qa.kids-first.io/#tag/Participant
     - should map to `participant.affected_status` 

Available as of Release v0.5.0

**Comment by rosibaj** [comment]
changes in kids-first/kf-es-model#36

**Comment by joneubank** [comment]
https://github.com/kids-first/kf-portal-etl/compare/feat/33-participant-fields?expand=1
