### ISSUE TITLE
Adjust Family Composition in ETL

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-etl#38]
- [ ] 1. `Family Type` added to Family
     - source: http://kf-api-dataservice-qa.kids-first.io/#tag/Family
     - Expected behaviour:  Right now the ETL is calculating a family relationship.  Rather than calculating this relationship, the field should be filled in from this value.  The structure should remain the same ( family members underneath etc)
- [ ] ~~4. `Source_Text_Notes` added to Family Relationship~~
    ~~-  source:http://kf-api-dataservice-qa.kids-first.io/#tag/FamilyRelationship~~ 
     ~~- should map to `family.family_compositions.family_members.source_text_notes` [TO BE CONFIRMED]~~ NOTE: after discussion with Allison, we will not add this due to confusion. 
- [ ] 2. `Family External ID` needs to be added to model
- [ ] 3.  Family was previously a nested object under family compositions.  Family composition has been removed and family is a standard object across all member, and is not nested.

Available as of Release v0.5.0

**Comment by rosibaj** [comment]
Related to: https://github.com/kids-first/kf-api-dataservice/issues/391

**Comment by rosibaj** [comment]
> R: We had originally designed the family compositions to be able to accept multiple family types for one participant --> for example you could be part of a `trio` and part of a `twin` set, each of which would have members specified (edited)
Is this part of your use-case set as to how people need to search?
Or are you expecting people to only want to identify participants into a single family type?

>A:ah yes - i didn't realize that, so in that case we could add multiplexed families as well as trios, yes? i think we quickly run into the "and" issue though.  people wanting participants that are `trio` and `twin` so i think that's why i had in my mind we weren't going to do that. we haven't really had any data that fits the use case yet and it might get confusing - i mean technically if you're in a `trio` you're also in a `duo`... but i think most people expect one or the other so you'd have some categories where you overlap and others where you say they're mutually exclusive

**Comment by rosibaj** [comment]
https://github.com/kids-first/kf-es-model/pull/36

**Comment by rosibaj** [comment]
After a discussion with Allison, they are thinking of restructuring the clinical/family arrangement in the near future. Due to this: 

- Currently, they are happy with the structure of the index and DO NOT want to adjust the index structure/data at all 
- The ```family_type``` field that was added to the data service will be removed and the data service will not calculate the family composition.
- As a result the proposal is that 2) and 3) in the list above are the only items that should be completed in future.

**Comment by rosibaj** [comment]
I believe that this is no longer needed - @allisonheath Can you confirm that you guys are ok with the current family structure until the dataservice relationship management is restructured?

**Comment by allisonheath** [comment]
@rosibaj that's correct, will keep as-is with the ETL calculating the family composition.
