### ISSUE TITLE
Define the ETL Architecture

### ISSUE THREAD

**Issue by Fgerthoffert** [kids-first/kf-portal-etl#4]
- [x] Track Data Release
- [ ] ID Generation (generalize ?)
- [ ] Export
- [ ] What to save ?
- [x] Framework

**Comment by andricDu** [comment]
Spark & Scala & Guice for lightweight DI

**Comment by andricDu** [comment]
Each index produced will have a release/build number to correspond to it.

**Comment by andricDu** [comment]
Closing ticket as both situation and scope have changed. 

Will wait for updates from CHOP and further discussions and direction on how data warehousing will be accomplished.
