### ISSUE TITLE
Diagnosis Category Rollup Field 

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-etl#50]
*Specs* https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/748027905/ETL+Calculations#ETLCalculations-DiagnosisCategory

**Comment by allisonheath** [comment]
I'm realizing that having any/all as an option in the facet would mean we wouldn't need to do this... just not sure how much work that is / if we'd still need this in the meantime.

**Comment by rosibaj** [comment]
Closing as this was completed
