### ISSUE TITLE
File external_id is blank in index

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-etl#55]
(https://github.com/kids-first/user-feedback/issues/94

**Sender**: bailey@d3b.center
**Comment**: Has this always been blank? I feel like this has changed recently to be blank? We have it set in teh data service.

<a href='https://usersnappublic.s3.amazonaws.com/2018-10-11/04-20/8f7230a9-f107-4982-b413-24c81e200141.png'>![usersnap- - File external id is blank](https://usersnappublic.s3.amazonaws.com/2018-10-11/04-20/d1f48720-1e96-44a7-8631-df8581cd5a00.jpg)</a>

**Comment by joneubank** [comment]
All phenotypes checked in data service have "null" for `external_id`

Check here:
http://kf-api-dataservice-qa.kids-first.io/phenotypes?limit=100
http://kf-api-dataservice.kids-first.io/phenotypes?limit=100

**Comment by rosibaj** [comment]
@joneubank this is file external id  tho, not phenotype external id
http://kf-api-dataservice-qa.kids-first.io/genomic-files/GF_851CMY87 
https://portal.kidsfirstdrc.org/search/file?sqon=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22filter%22%2C%22content%22%3A%7B%22fields%22%3A%5B%22kf_id%22%2C%22participants.kf_id%22%2C%22participants.study.short_name%22%2C%22participants.family_id%22%2C%22data_type%22%2C%22file_format%22%2C%22external_id%22%5D%2C%22value%22%3A%22GF_851CMY87%22%7D%7D%5D%7D
