### ISSUE TITLE
Update Ontological Fields to text (ID) format for values

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-etl#66]
Currently, ontological ID fields contain the ID only.  We want to translate the values in these to a more readable format for users.  The new format will be text_value_of_ontology_term (Onltology ID) 
> NOTE: Final values should be in sentence case

Each of these fields needs to be transformed in this manner:

- [ ] biosepcimen.ncit_id_anatomical_site
-- Current Value: `NCIT:C12438`
-- Expected Value: `Central nervous system (NCIT:C12438)`

- [ ] biosepcimen.ncit_id_tissue_type
-- Current Value: `NCIT:C14165`
-- Expected Value: `Normal (NCIT:C14165)`

- [ ] diagnoses.diagnosis
-- Current Value: `medulloblastoma`
-- Expected Value: `Medulloblastoma (MONDO:0007959) `
** note- for this field sometimes the value will be NCIT ids; if none then source text is used.  in that case, there should be no id.

- [ ] phenotype.ancestral_hpo_ids
-- Current Value:
-- Expected Value:

- [ ] phenotype.hpo_phenotype_not_observed
-- Current Value: `HP:0000508`
-- Expected Value: `Ptosis (HP:0000508)`

- [ ] phenotype.hpo_phenotype_observed
-- Current Value: `HP:0012638`
-- Expected Value: `Abnormality of nervous system physiology (HP:0012638)`

**Comment by jecos** [comment]
This is a suggestion on what to do :
### Diagnosis and Biospecimens
- Rename **Mondo ID Diagnosis** with **Diagnosis (Mondo)**
-- Values will be _Mondo term (Mondo ID)_
- Same for **NCit ID Diagnosis** i.e field name will be renamed with **Diagnosis (NCit)**
- Same for **NCit ID Tissue type**
- Same for **NCit ID ANatomical Site**
- Same for Share **HPO ids** ( replace with **Shared Phenotype (HPO)** )
- Need to decide what we do with the Diagnosis Field

### Phenotypes
- Rename **Observed Phenotype** with **Observed Phenotype (HPO)**
-- Values are already in the right format i.e. term (ID)
- Do the same for **Not Observed Phenotype**
- Remove field **HPO phenotype not observed** and **HPO phenotype Observed**

**Comment by rosibaj** [comment]
@jecos @aalex just added this as a resource to help explain any business logic if needed: https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/748027905/ETL+Calculations

**Comment by jecos** [comment]
thanks @rosibaj ! Quick question for you, what is the purpose of phenotype.ancestral_hpo_ids. My understanding is that it should index the parent term of a given phenotype. But 
1) It seems to be bugged (I think value in elastic search is not what is expected).
2) This field is never used in the portal (neither explore data or file repository).

Should we remove this field from the elastic search index?

**Comment by rosibaj** [comment]
@jecos Yes, the original feature this field was supposed to be used for was in fact deprioritized.  The intent was to include `all` parent terms to any term a participant has assigned.  I don't see an issue removing this, but Vincent/Alex should make the decision on this.

**Comment by vferretti** [comment]
yes please remove for the moment
