### ISSUE TITLE
The phenotypes for each participant are missing

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-etl#90]
As a user, I want to be able to display all the phenotypes for a user, so that I can see which variant or diagnosis is related to them.

## Acceptance criteria
- The ETL should make sure that the participant-centric index provides potentially multiple phenotypes for a participant.
- It should provide each of the types listed below

## List of the supported fields
- Observed Phenotypes (HPO)
- Not Observed Phenotypes (HPO)
- Phenotypes (Source Text) 

## Technical details
It's currently not possible to do because when we query a participant its phenotypes are simply not in the results.

One also notices that the phenotype field in graphql is named "phenotype" whereas all other fields that can have multiple results are plural. In other words, diagnoses is plural and when we query it it returns an array of diagnosis ("hits edges node"). Phenotype should logically return an array of phenotypes, but the graphql query directly asks for the phenotype's data, without an "hits edges node" pattern.

The ETL might be broken for those. @Velythyl thinks the file explorer works with phenotypes because it asks them relating to the files, not the participants.

**Comment by aalex** [comment]
Probably that the `phenotype` (sic) field should be of `nested` type, and not `object`.

**Comment by jberube** [comment]
List of places to test (as per `kf-portal-ui` source code) :
- Virtual Studies. fields related to phenotypes (in _Clinical_) and _Search All_.
- The example query _"Female probands with cleft palate (HP:0000175) and parents with harmonized aligned reads"_ in the _Dashboard_
- Phenotypes information in the _File Entity Page_
- Facets concerning phneotypes in the _File Repository_
- Download button in _File Repository_ table
